FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block horizon_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='horizon') }}

{% if base_package_type == 'rpm' %}

    {% set horizon_packages = [
        'gettext'
    ] %}

{{ macros.install_packages(horizon_packages | customizable("packages")) }}
{% elif base_package_type == 'deb' %}

    {% set horizon_packages = [
        'gettext',
        'locales',
        'tzdata'
    ] %}

{{ macros.install_packages(horizon_packages | customizable("packages")) }}

{% block horizon_ubuntu_source_setup %}
RUN ln -s ../mods-available/headers.load  /etc/apache2/mods-enabled/headers.load
{% endblock %}

{% endif %}

ADD horizon-archive /horizon-source
ADD plugins-archive /

{% set horizon_pip_packages = [
    '/horizon'
] %}

{% set horizon_plugins_pip_packages = [
    '/plugins/*'
] %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

# NOTE(hrw): to install horizon from unpacked sources we cannot have it in upper-constraints.txt
RUN ln -s horizon-source/* horizon \
    # NOTE(mnasiadka): pinning setuptools due to https://bugs.launchpad.net/horizon/+bug/2007574
    && {{ macros.install_pip(['setuptools==67.2.*']) }} \
    # See https://bugs.launchpad.net/horizon/+bug/2007574
    && curl -L https://files.pythonhosted.org/packages/source/X/XStatic-Moment-Timezone/XStatic-Moment-Timezone-0.5.22.0.tar.gz -o xstatic.tar.gz \
    && mkdir -p storage && tar -xf xstatic.tar.gz -C storage --strip-components=1 \
    && cd storage \
    && sed -i "1 s/^/import pkg_resources\n/" setup.py \
    && /var/lib/kolla/venv/bin/python3 setup.py install \
    && cd ../ \
    && rm -rf storage xstatic.tar.gz \
    && {{ macros.upper_constraints_remove("horizon") }} \
    && PBR_VERSION=99.99.9 python3 -m pip install --upgrade --no-build-isolation --no-cache-dir -c /requirements/upper-constraints.txt /horizon \
    && mkdir -p /etc/openstack-dashboard \
    && cp -r /horizon/openstack_dashboard/conf/* /etc/openstack-dashboard/ \
    && cp /horizon/openstack_dashboard/local/local_settings.py.example /etc/openstack-dashboard/local_settings \
    && cp /horizon/manage.py /var/lib/kolla/venv/bin/manage.py \
    && if [ "$(ls /plugins)" ]; then \
           {{ macros.install_pip(horizon_plugins_pip_packages) }}; \
       fi \
    && for locale in  /var/lib/kolla/venv/lib/python{{distro_python_version}}/site-packages/*/locale; do \
           (cd ${locale%/*} && /var/lib/kolla/venv/bin/django-admin compilemessages) \
       done \
    && chmod 644 /usr/local/bin/kolla_extend_start

{% block horizon_footer %}{% endblock %}
{% block footer %}{% endblock %}
